NOTES_DIR = "notes"
SESSION_TYPE = "filesystem"
# override this with an environment variable when running somewhere other than
# localhost
SERVER_NAME = 'localhost:8000'

# dropbox config
[DROPBOX]
AUTHORIZE_URI = "https://www.dropbox.com/oauth2/authorize"
TOKEN_URI = "https://api.dropboxapi.com/oauth2/token"
